<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <iframe src="/dashboard-assets/widgets/rss/relogios.html" class="bloco-relogios" frameborder="0" id="frame-relogios" width="100%" scrolling="no"></iframe>
    </div>
    <br />
    <div class="col-md-12" >
        <div id="qtd-abertos-estados" class="uma-metade"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="">
            <table class="table equal-3 head-fixo">
                <thead>
                <tr>
                    <th>Município</th>
                    <th>Título</th>
                    <th>Categoria</th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="uma-metade menos-frame-relogio rodar-tabela">
            <table class="table equal-3 table-condensed table-striped">
                <tbody class="tbody-estado"></tbody>
            </table>
        </div>
    </div>
</div>