<div class="row">
    <div class="col-md-12">
        <div id="categoria-subcategoria-uf" class="uma-metade"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div id="total-registros-por-situacao" class="uma-metade"></div>
    </div>
    <div class="col-md-8">
        <div class="uma-metade">
            <div class="">
                <table class="table equal-4 head-fixo dark-blue">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Título</th>
                            <th>Situação</th>
                            <th>Data Criação</th>
                            <th>Nível</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="uma-metade rodar-tabela" id="lista-alertas">
                <table class="table dark-blue equal-4 table-condensed">
                    <tbody class="tbody-alertas"></tbody>
                </table>
            </div>
        </div>
    </div>
</div>