<div class="row">
    <div class="col-md-12">
        <div id="uf-categoria-subcategoria" class="uma-metade"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div id="uf-nivel" class="uma-metade"></div>
<!--        <div id="total-registros-por-situacao-b" class="uma-metade"></div>-->
<!--        <div id="top-10-usuarios" class="uma-metade"></div>-->
    </div>
    <div class="col-md-4">
        <div id="total-ocorrencias" class="uma-metade"></div>
    </div>
</div>