<?php $versao = 'versão 1.0'; ?>

<div class="container">
    <nav class="navbar navbar-transparent footer blackblue">
        <div class="row">
            <div class="col-md-6">
                <p class="small text-muted"><a href="modulo.com.br" class="text-muted" target="_blank">Powered by Módulo | 2016 <?= $versao ?></a></p>
            </div>
            <div class="col-md-6">
                <p class="text-right small text-muted"><?= $versao ?></p>
            </div>
        </div>
    </nav>
</div>