<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sLaminas%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('This module is running on Laminas MVC.') ?></p>
    <p><a class="btn btn-success btn-lg" href="https://getlaminas.org/" target="_blank"><?php echo $this->translate('Laminas Project') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Laminas continues the Zend Framework project under the Laminas Project packages.') ?></p>
                <p><a class="btn btn-success pull-right" href="https://docs.laminas.dev/" target="_blank"><?php echo $this->translate('Laminas Documentation') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Laminas modules and components are published as Composer packages.') ?></p>
                <p><a class="btn btn-success pull-right" href="https://packagist.org/?query=laminas" target="_blank"><?php echo $this->translate('Explore Laminas Packages') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
