<div class="row">
    <div class="col-md-12">
        <div class="rodar-tabela">
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>UF</th>
                    <th>Município</th>
                    <th>Nome Escola</th>
                    <th>Situação</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($lista as $value){?>
                    <tr>
                        <td><?=$value['UF']?></td>
                        <td><?=$value['MUNICIPIO']?></td>
                        <td><?=$value['NOME_ESCOLA']?></td>
                        <td><?=$value['STATUS']?></td>
                    </tr>
                <?php }; ?>
                </tbody>
                <?php if(!count($lista)){?>
                    <tbody>
                        <td colspan="4" class="text-center">Sem Registros</td>
                    </tbody>
                <?php };?>
            </table>
        </div>
    </div>
</div>