<div class="container-fluid content menu" data-menu="Diagrama de Gantt">
    <div class="row content-title">
        <h1>Diagrama de Gantt
            <span class="pull-right">
                <a href="/" class="voltar">
                    <i class="fa fa-caret-left"></i> Voltar
                </a>
            </span>
        </h1>

    </div>

    <div class="row">
        <div class="col-md-11">
            <div id="gantt" class="gantt"></div>
        </div>
        <div class="col-md-1" style="padding-top: 50px">
            <strong>Legenda:</strong><br>
            <ul class="legenda"></ul>
        </div>
    </div>
    <br><br>
</div>

<?= $this->render('modal-detalhes-evento') ?>