<?php echo $this->doctype(); ?>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('.::Ajuda - Painel de Monitoramento::.') ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link rel="shortcut icon" href="<?= $this->basePath('/assets/img/logo/favicon-64.ico'); ?>">

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/icon/fav.ico'))
        ->prependStylesheet($this->basePath('ajuda-assets/css/mobile.css'))
        ->prependStylesheet($this->basePath('ajuda-assets/css/main.css'))
        ->prependStylesheet($this->basePath('assets/fontawesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap-material-design/css/ripples.min.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap-material-design/css/material.min.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap-material-design/css/roboto.min.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.min.css')) ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/assets/js/html5shiv.js"></script>
    <script src="/assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<?=$this->content;?>

<script src="/assets/jquery/jquery-1.11.3.min.js"></script>
<script src="/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="/assets/bootstrap-material-design/js/material.min.js"></script>
<script src="/assets/bootstrap-material-design/js/ripples.min.js"></script>
<script src="/ajuda-assets/js/main.js"></script>

</body>
</html>