<?php
$id = $id ?? '';
$title = $title ?? '';
$body = $body ?? '';
$footer = $footer ?? '';
$size = $size ?? '';
?>
<div class="modal fade" id="<?= $this->escapeHtmlAttr($id) ?>" aria-hidden="true">
    <div class="modal-dialog <?= $this->escapeHtmlAttr($size) ?>">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title h5"><?= $this->escapeHtml($title) ?></h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body"><?= $body ?></div>
            <?php if ($footer) : ?>
                <div class="modal-footer"><?= $footer ?></div>
            <?php endif; ?>
        </div>
    </div>
</div>
