<div class="row">
    <div class="col-xs-12">
        <div class="confirmacao-box">
            
            <div class="confirmacao-header">
                <span class="glyphicon glyphicon-ok-sign confirmacao-icon"></span>
                <h3 class="confirmacao-title">Ocorrência cadastrada com sucesso!</h3>
            </div>


            <a href="<?php echo $this->url('mobile', ['action' => 'cadastro-ocorrencia']); ?>" class="btn btn-primary btn-lg btn-block">
                <span class="glyphicon glyphicon-plus"></span> Cadastrar Nova Ocorrência
            </a>
        </div>
    </div>
</div>