<div class="logo-me">
<!--    <a href=""><img src="/assets-cgi/img/logo/somostodosbrasil.jpg" alt=""></a>-->
</div>

<div id="first-block" class="block-full bg-me">
<!--    <img src="/ajuda-assets/img/mao-iphone-cgi.png" alt="">-->
</div>

<div class="title-wrap">
    <div>
        <h1>Monitore, registre, participe!</h1>
        <br>
        <h4>Baixe o manual de uso da aplicação Painel de Monitoramento</h4>
        <p><a href="/ajuda/download-manual" target="_blank" class="btn btn-raised buttom-block">BAIXAR</a></p>
    </div>
</div>

<div id="third-block" class="block-full bg-yellow">
    <div class="row">
        <div class="col-md-12">
            <div class="wrap-features">
                <div class="linha">
                    <div>
                        <a href="#" data-toggle="modal" data-target="#video" data-video="ocorrencia.mp4" data-title="Registrando uma ocorrência">
                            <img src="/ajuda-assets/img/ocorrencia.png" alt="">
                        </a>
                    </div>
                    <div>Registre ocorrência</div>
                </div>
                <div class="linha">
                    <div>
                        <a href="#" data-toggle="modal" data-target="#video" data-video="triagem.mp4" data-title="Elaborando uma triagem">
                            <img src="/ajuda-assets/img/questionario.png" alt="">
                        </a>
                    </div>
                    <div>Faça a triagem, classifique a ocorrência e gere o alerta.</div>
                </div>
                <div class="linha">
                    <div>
                        <a href="#" data-toggle="modal" data-target="#video" data-video="atualizando-progresso.mp4" data-title="Atualizando progresso">
                            <img src="/ajuda-assets/img/monitore.png" alt="">
                        </a>
                    </div>
                    <div>Monitore e atualize progresso do alerta.</div>
                </div>
                <div class="linha">
                    <div>
                        <a href="#" data-toggle="modal" data-target="#video" data-video="dashboard.mp4" data-title="Visualizando o dashboard">
                            <img src="/ajuda-assets/img/acompanhe.png" alt="">
                        </a>
                    </div>
                    <div>Acompanhe a aplicação por meio do painel de monitoramento.</div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="video">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">&nbsp;</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <video width="100%" height="auto" controls>
                            <source src="" type="video/mp4">
                        </video>
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->