<?php

return array(
    'modules' => array(
        'Laminas\Serializer',
        'Laminas\Navigation',
        'Laminas\Mvc\Plugin\FilePrg',
        'Laminas\Mvc\Plugin\FlashMessenger',
        'Laminas\Mvc\Plugin\Identity',
        'Laminas\Mvc\Plugin\Prg',
        'Laminas\Session',
        'Laminas\Mvc\I18n',
        'Laminas\I18n',
        'Laminas\Router',
        'Laminas\Mail',
        'Laminas\Log',
        'Laminas\Form',
        'Laminas\Hydrator',
        'Laminas\InputFilter',
        'Laminas\Filter',
        'Laminas\Validator',
        'Laminas\Di',
        'Laminas\Db',
        'Laminas\Cache',
        'Laminas\Cache\Storage\Adapter\Filesystem',
        //'Laminas\ZendFrameworkBridge',
        'Application',
        'Dashboard',
        'Autenticacao',
        'Usuario',
        'Estrutura',
       // 'DOMPDFModule',
        'Gerador',
        'Modulo',
        'RiskManager',
        'Base',
        'Mobile',
        'Classes',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
            './vendor/moduloapi',
        ),
        'config_glob_paths' => array(
            'config/autoload/global.php',
        ),
    ),
);
