<?php $urlPainel = \Estrutura\Service\Config::getConfig('url_painel'); ?>
<!--<div class="row">-->
<!--    <div class="col-md-12">-->
<!--        <iframe src="http://inep.ctweb.inweb.org.br/dashboard/analise/exibir/5?w=full" frameborder="0" id="frame-media-twitter" class="dois-terco" width="100%"></iframe>-->
<!--    </div>-->
<!--</div>-->

<div class="row">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <!--Primeira leva de Twitter-->
                <div class="item active">

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem" data-widget-id="654037113604845568">Tweets sobre enem</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Inep</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" href="https://twitter.com/search?q=inep" data-widget-id="654038665665085440">Tweets sobre inep</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Cartão+Confirmação</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bcart%C3%A3o%2Bconfirma%C3%A7%C3%A3o" data-widget-id="654041585559150592">Tweets sobre enem+cartão+confirmação</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Redação</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Breda%C3%A7%C3%A3o" data-widget-id="654276899573760000">Tweets sobre enem+redação</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Tema+Redação</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Btema%2Breda%C3%A7%C3%A3o" data-widget-id="654277360783654912">Tweets sobre enem+tema+redação</a>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Erro</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Berro" data-widget-id="654277655332802560">Tweets sobre enem+erro</a>
                        </div>
                    </div>

                </div>

                <!--Segunda leva de Twitter-->
                <div class="item">
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Problema</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bproblema" data-widget-id="654288311146692608">Tweets sobre enem+problema</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Vazamento</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bvazamento" data-widget-id="654288656086249472">Tweets sobre enem+vazamento</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Fraude</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bfraude" data-widget-id="654288947972046848">Tweets sobre enem+fraude</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Cespe</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bcespe" data-widget-id="654289199324098560">Tweets sobre enem+cespe</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Cesgranrio</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=cesgranrio" data-widget-id="654289481219076096">Tweets sobre cesgranrio</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Fiscal</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bfiscal" data-widget-id="654289853128028160">Tweets sobre enem+fiscal</a>
                        </div>
                    </div>
                </div>

                <!--Terceira leva de Twitter-->
                <div class="item">
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Coordenador</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bcoordenador" data-widget-id="654334983415406592">Tweets sobre enem+coordenador</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Chefe+Sala</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bchefe%2Bsala" data-widget-id="654335551999504384">Tweets sobre enem+chefe+sala</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Folha+Resposta</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bfolha%2Bresposta" data-widget-id="654335946238894080">Tweets sobre enem+folha+resposta</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Local+Prova</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Blocal%2Bprova" data-widget-id="654336463295938560">Tweets sobre enem+local+prova</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Sala+Prova</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=Enem%2BSala%2BProva" data-widget-id="654337831284940800">Tweets sobre Enem+Sala+Prova</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Atendimento</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Batendimento" data-widget-id="654338249968746497">Tweets sobre enem+atendimento</a>
                        </div>
                    </div>

                </div>

                <!--Quarta leva de Twitter-->
                <div class="item">
                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Sabatista</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bsabatista" data-widget-id="654342988454305794">Tweets sobre enem+sabatista</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+MEC</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bmec" data-widget-id="654343695731441664">Tweets sobre enem+mec</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Mercadante</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bmercadante" data-widget-id="654343937465913344">Tweets sobre enem+mercadante</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Cola</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bcola" data-widget-id="654344215690899456">Tweets sobre enem+cola</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Gabarito</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bgabarito" data-widget-id="654344506926628864">Tweets sobre enem+gabarito</a>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="dois-terco">
                            <div class="sobre-coluna-twitter">
                                <h5>Enem+Venda</h5>
                            </div>
                            <a class="twitter-timeline" data-chrome="nofooter noheader noscrollbar transparent" data-dnt="true" href="https://twitter.com/search?q=enem%2Bvenda" data-widget-id="654344791912808453">Tweets sobre enem+venda</a>
                        </div>
                    </div>

                </div>

            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <iframe src="/dashboard-assets/widgets/rss/rss.html" frameborder="0" id="frame-media-rss" class="um-terco" width="100%"></iframe>
    </div>
</div>