<!DOCTYPE html>
<html>
<head>
    <title><?=$this->Projeto()?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css"/>
    <script src="/assets/jquery/jquery-1.11.1.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<style>
    table,tr,td,th{
        font-size: 10px !important;;
        padding: 5px !important;;
        margin: 5px !important;
    }
    thead{
        background-color: #000;
        color:#fff
    }
</style>
<?=$this->content?>
</body>
</html>
