<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
<div class="row">
    <div class="block-flat">
        <div class="content">
    <?php

                $form->setAttribute('action', $this->url('application', array('controller'=>$controller,'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('Id'));
                ?>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Nome'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('DataNascimento'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('RegistroControle'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Venue'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Evento'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('StatusCredencial'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Organizaã‡ãƒo'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Genero'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('IdFuncaoEvento'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('IdNacionalidade'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Cpf'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Documento'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('IdTipoDocumento'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('AutoridadeEmissora'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('DataExpedicao'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('DataValidadePassaporte'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('NomeMae'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('NomePai'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Endereco'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Bairro'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Cep'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Municipio'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Estado'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('IdPaisOrigem'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('StatusConsolidadoBgc'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('Foto'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('StatusSistema'))?>
                    </div>
                </div>

                
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-default">Salvar</button>
                        <a href="<?=$this->url('application', ['controller'=>$controller])?>" class="btn btn-warning">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
        </div></div>
    </div>
</div>