<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="aplicacao">
        <?=$this->render('pag-aplicacao')?>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="alertas">
        <?=$this->render('pag-alertas')?>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="estados">
        <?=$this->render('pag-estados')?>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="mapa">
        <?=$this->render('pag-mapa')?>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="midia">
        <?=$this->render('pag-midia')?>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="ultima-milha">
        <?=$this->render('pag-ultima-milha')?>
    </div>
</div>