<div class="row">
    <div class="col-md-12" >
        <div id="qtd-abertos-etapa-processo" class="um-terco"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div id="qtd-abertos-etapa-processo-pizza" class="pizza-alertas um-terco"></div>
    </div>
    <div class="col-md-4">
        <div id="qtd-abertos-etapa-pizza" class="pizza-alertas um-terco"></div>
    </div>
    <div class="col-md-4">
        <div id="qtd-fechados-etapa-pizza" class="pizza-alertas um-terco"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="">
            <table class="table head-fixo">
                <thead>
                <tr>
                    <th class="fx-20">Nível</th>
                    <th class="fx-40">Título</th>
                    <th class="fx-40">Etapa do Processo</th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="um-terco rodar-tabela">
            <table class="table table-pag-alertas table-condensed table-striped">
                <tbody class="tbody-etapa"></tbody>
            </table>
        </div>
    </div>
</div>

<!--<div class="row">-->
<!--    <div class="col-md-12">-->
<!--        <table class="table table-pag-alertas table-condensed">-->
<!--            <thead>-->
<!--            <tr>-->
<!--                <th class="fx-200">Nível</th>-->
<!--                <th>Título</th>-->
<!--                <th>Etapa do Processo</th>-->
<!--            </tr>-->
<!--            </thead>-->
<!--        </table>-->
<!--        <div class="rodar-tabela">-->
<!--            <table class="table table-pag-alertas table-condensed">-->
<!--                <tbody class="tbody-etapa">-->
<!---->
<!--                </tbody>-->
<!--            </table>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->