<div class="row">
    <div class="col-md-12">
        <div id="linha-tempo-usuarios-online" class="uma-metade"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="uma-metade">
            <div class="">
                <table class="table equal-3 head-fixo dark-blue">
                    <thead>
                    <tr>
                        <th>Usuário</th>
                        <th>IP</th>
                        <th>Navegador</th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="uma-metade rodar-tabela" id="usuarios-online">
                <table class="table dark-blue equal-3 table-condensed">
                    <tbody class="tbody-usuarios"></tbody>
                </table>
            </div>
        </div>
    </div>
</div>