<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="pt-BR">
<head>
    <title><?= $this->Projeto() ?></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="<?= $this->basePath('/assets/img/logo/favicon-64.ico'); ?>">

    <!--Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/dashboard-assets/css/bootstrap.superhero.theme.min.css">
    <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/dashboard-assets/css/customizado.css">

</head>

<body>

<div class="container-fluid">
    <?=$this->render('abas/dashboard')?>
    <?=$this->content?>
</div>

<div class="modal fade" id="modal-configuracao">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Configurações</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="habilitar-alternar-abas"/>
                                alternar abas selecionadas
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="">alternar em segundos</label>
                            <input type="number" class="form-control" min="10" value="10" name="segundos-alternar-abas"/>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-sm btn-primary botao-salvar-alternador-paginas">Salvar</button>
                        </div>
                    </div>
                </div>

                <hr/>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="">Filtro Twitter</label>
                            <textarea name="words-twitter" class="form-control" cols="30" rows="3"></textarea>
                            <p class="help-block">Separar palavras ou conjunto de palavras por ; (ponto e vírgula)</p>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-sm btn-primary botao-salvar-filtro-twitter">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="modal-detalhes-evento">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 alerta-dados"></div>
                    <div class="col-md-6 alerta-atualizacoes"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="form-detalhes">
    <form action="/dashboard-data/lista-eventos" method="post" target="_blank" id="formListaEventos">
        <input type="hidden" name="get" value="aplicacao-categoria">
        <input type="hidden" name="color" value="#90ee7e">
        <input type="hidden" name="category" value="Segurança Pública">
        <input type="hidden" name="status" value="">
    </form>
</div>

<script type="text/javascript" src="/assets/jquery/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript" src="/assets/clock/jquery.clock.js"></script>

<script type="text/javascript" src="/assets/marquee/jquery.marquee.min.js"></script>
<script type="text/javascript" src="/assets/stickytableheaders/jquery.stickytableheaders.min.js"></script>

<script type="text/javascript" src="/assets/highchart/full/highcharts.js"></script>
<script type="text/javascript" src="/dashboard-assets/js/highcharts-more.js"></script>
<script type="text/javascript" src="/dashboard-assets/js/dark-unica.js"></script>
<script type="text/javascript" src="/dashboard-assets/js/solid-gauge.js"></script>

<script type="text/javascript" src="/assets/moment/moment.js"></script>
<script type="text/javascript" src="/assets/moment/moment-with-locales.js"></script>
<script type="text/javascript" src="/assets/moment/moment-timezone-with-data-2010-2020.js"></script>

<script type="text/javascript" src="/dashboard-assets/js/customizado.js"></script>
<script type="text/javascript" src="/dashboard-assets/js/charts.js"></script>
<script type="text/javascript" src="/dashboard-assets/js/twitter.js"></script>

</body>
</html>