<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="panel panel-default" style="margin-top: 100px;">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="page-header text-center">
                                <img src="<?=$this->basePath('/assets/img/ico/ico_no_auth.png')?>"> Acesso Não Autorizado
                            </h1>
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <div class="col-md-12">
                            Você não possui permissão de acesso a esta página.<br>
                            Caso seja necessário acessá-la, solicite ao administrador do sistema as permissões adequadas ao seu perfil ou seu papel.
                            <br><br>
                            <a href="<?=$this->basePath("/")?>" class="voltar">
                                Clique aqui para voltar
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>